### ISSUE TITLE
False positive on stairs

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#284]
On **godseye.nort721.com**

Some false positives when you going up on stairs.

https://i.ibb.co/9t13VPK/ezgif-2-2ee7f72f9c0a.gif

**Comment by Nort721** [comment]
Can't seem to replicate this issue after testing it a lot, it might happen because you used speed before and your VL was still pretty high, maybe, not sure

If you manage to replicate it again with a Vanilla client comment this issue and I will reopen it and recheck it

*currently closed since I couldn't seem to replicate it*
