### ISSUE TITLE
Strange bug with snow

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#286]
On **godseye.nort721.com**

https://i.ibb.co/hHFxWgc/ezgif-2-7be282ece521.gif

**Comment by Nort721** [comment]
Ok so first of all that doesn't seem to be a bug that's related to GodsEye since GodsEye doesn't send any logs when it happens, this also seems to only happen in later versions (I tested with 1.8.9 and it didn't happen but did happen in 1.16.4), also it keeps on happening even when I remove GodsEye from the test server and only happens on these specific snow piles at this specific location, from all of that seems like its a Minecraft bug, not a GodsEye bug
