### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by KoxSosen** [Nort721/GodsEye#379]
A bug report/issue report should contain:

1) GodsEye vbuild 45
2) git-Airplane-"f5fb024" (MC: 1.16.5)
3) ProtocolLib v4.6.1-SNAPSHOT-b499
4) https://paste.hahota.net/3AijQ716ZH
5) No video evidence
6) Random error in the console after a player left.

**Comment by TehSteel** [comment]
I've added a bug label, wait for @Nort721 responses.

**Comment by Nort721** [comment]
Pretty sure this got fixed in one of the last releases, anyhow seems like it doesn't happen in the latest version so update to the latest version and I assume this issue is solved, if your still having this issue when running the current latest version please contact us on discord and we will reopen the issue or, open a new issue ticket
