### ISSUE TITLE
Issue with false detection

### ISSUE THREAD

**Issue by SexyEis** [Nort721/GodsEye#385]
A bug report/issue report should contain:

1) newest
2) Paper 1.16.5
3) newest
4) The alerts dont show in the Console
5) Here are the Screenshots (thats only a few)
![2021-05-30_13 29 47](https://user-images.githubusercontent.com/84544952/120102519-b5b24800-c14b-11eb-8b32-0bfa677b5a3d.png)
![2021-05-30_13 29 37](https://user-images.githubusercontent.com/84544952/120102520-b6e37500-c14b-11eb-90a0-e5c5e4d9a437.png)

6) many people get detected for using "scaffold,reach,fly,timer or even speed but aren´t really hacking" i didnt chane anything in the coinfg/checks.yml either

**Comment by Nort721** [comment]
How did you verify that they are not hacking?

**Comment by SexyEis** [comment]
I was next to them because at first i thought they were but as i was next to them they dont but the Anticheat didnt stop to report

**Comment by SexyEis** [comment]
Do you have a optimal Version of the Checks.yml for me?

**Comment by Nort721** [comment]
I'll net the Type TypeD false positives are caused by the slow falling issue which we are fixing the next update, idk about the reach though, thats a cheat that also would be hard to catch even when looking at the player, only thing I can recommend is to increase max flags in checks.yml, for the teleport check false you can increase the max blocks per ticks from 8 to a bigger number like 10 or 15, don't make it too big though

**Comment by Nort721** [comment]
hey there, did you edit your checks.yml as I said, does the issue still exist in the latest version?
