### ISSUE TITLE
ProtocolLib error

### ISSUE THREAD

**Issue by SadRusty** [Nort721/GodsEye#417]
1) Build 49 HotFix-3
2) 1.17.1 Purpur\Spigot\Airplane
3) ProtoclLib 4.7.0 & 4.7.1
4) [Server log](https://pastebin.com/jTfniC56)
6) [ProtocolLib] [PacketFilterManager] [GodsEye] Unsupported server packet in current Minecraft version

**Comment by Izibane** [comment]
isnt an error?

**Comment by SadRusty** [comment]
> isnt an error?

The plugin does not work because of this

**Comment by Nort721** [comment]
Well I've implemented some changes in the code to only register supported packets relative to the server version which should prevent ProtocolLib from showing these messages but its not an error and doesn't affect the plugins performance at all

You wrote that you have two different versions of ProtocoLlib running on your server? if that's the case that's probably what causes GodsEye to malfunction, otherwise it should work just fine
